"""Initial migration

Revision ID: c8dd016dc1b6
Revises: 
Create Date: 2025-10-04 18:37:43.792343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8dd016dc1b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_historical_data_id'), 'historical_data', ['id'], unique=False)
    op.create_index(op.f('ix_historical_data_price_date'), 'historical_data', ['price_date'], unique=False)
    op.create_index(op.f('ix_historical_data_symbol'), 'historical_data', ['symbol'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('annualized_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_dividends', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('annual_dividend_projection', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sector_allocation', sa.JSON(), nullable=True),
    sa.Column('country_allocation', sa.JSON(), nullable=True),
    sa.Column('asset_type_allocation', sa.JSON(), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_category', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='riskcategoryenum'), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('pies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_invest', sa.Boolean(), nullable=False),
    sa.Column('target_allocation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('annualized_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('time_weighted_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('portfolio_contribution', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('portfolio_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_dividends', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('monthly_dividend_avg', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_category', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='riskcategoryenum'), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_rebalanced', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pies_id'), 'pies', ['id'], unique=False)
    op.create_index(op.f('ix_pies_portfolio_id'), 'pies', ['portfolio_id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('pie_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('security_name', sa.String(), nullable=False),
    sa.Column('dividend_type', sa.Enum('CASH', 'STOCK', 'REINVESTED', name='dividendtypeenum'), nullable=False),
    sa.Column('amount_per_share', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('shares_held', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('ex_dividend_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_withheld', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('base_currency_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_reinvested', sa.Boolean(), nullable=False),
    sa.Column('reinvested_shares', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('reinvestment_price', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pie_id'], ['pies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.create_index(op.f('ix_dividends_pie_id'), 'dividends', ['pie_id'], unique=False)
    op.create_index(op.f('ix_dividends_portfolio_id'), 'dividends', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('pie_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('start_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('end_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('dividends_received', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('contributions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('withdrawals', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pie_id'], ['pies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_id'), 'performance_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_pie_id'), 'performance_snapshots', ['pie_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_portfolio_id'), 'performance_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_snapshot_date'), 'performance_snapshots', ['snapshot_date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('pie_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'CRYPTO', 'BOND', 'COMMODITY', 'CASH', name='assettypeenum'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pie_id'], ['pies.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_pie_id'), 'positions', ['pie_id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_pie_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_performance_snapshots_snapshot_date'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_portfolio_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_pie_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_portfolio_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_pie_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_pies_portfolio_id'), table_name='pies')
    op.drop_index(op.f('ix_pies_id'), table_name='pies')
    op.drop_table('pies')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_historical_data_symbol'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_price_date'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_id'), table_name='historical_data')
    op.drop_table('historical_data')
    # ### end Alembic commands ###
